#各个微服务对应的配置文件
server:
  port: 8030

spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
  instance:
    prefer-ip-address: true