#各个微服务对应的配置文件

server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_food?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver